#pragma once
#include "vikings.hpp"

enum Buttons
{
	BUTTON_UNK0        = BIT(0),
	BUTTON_UNK1        = BIT(1),
	BUTTON_UNK2        = BIT(2),
	BUTTON_UNK3        = BIT(3),
	BUTTON_NEXTCHAR    = BIT(4),
	BUTTON_PREVCHAR    = BIT(5),
	BUTTON_USEITEM     = BIT(6),
	BUTTON_ACTIVATE    = BIT(7),
	BUTTON_RIGHT       = BIT(8),
	BUTTON_LEFT        = BIT(9),
	BUTTON_DOWN        = BIT(10),
	BUTTON_UP          = BIT(11),
	BUTTON_PAUSE       = BIT(12),
	BUTTON_INVENTORY   = BIT(13),
	BUTTON_SPECIAL     = BIT(14),
	BUTTON_ATTACK      = BIT(15)
};

// Scancodes as generated by an XT keyboard (PS/2 Scancode set 1, NOT 2)
enum XTScancodes
{
	SCAN_ESCAPE       = 0x01,
	SCAN_TAB          = 0x0F,
	SCAN_Q            = 0x10,
	SCAN_E            = 0x12,
	SCAN_P            = 0x19,
	SCAN_RETURN       = 0x1C,
	SCAN_CTRL         = 0x1D,
	SCAN_S            = 0x1F,
	SCAN_D            = 0x20,
	SCAN_F            = 0x21,
	SCAN_X            = 0x2D,
	SCAN_M            = 0x32,
	SCAN_ALT          = 0x38,
	SCAN_SPACEBAR     = 0x39,
	SCAN_CAPSLOCK     = 0x3A,
	SCAN_F4           = 0x3E,
	SCAN_F5           = 0x3F,
	SCAN_F6           = 0x40,
	SCAN_F10          = 0x44,
	SCAN_KP7_HOME     = 0x47,
	SCAN_KP8_UP       = 0x48,
	SCAN_KP9_PAGEUP   = 0x49,
	SCAN_KP4_LEFT     = 0x4B,
	SCAN_KP5          = 0x4C,
	SCAN_KP6_RIGHT    = 0x4D,
	SCAN_KPPLUS       = 0x4E,
	SCAN_KP2_DOWN     = 0x50,
	SCAN_KP0_INSERT   = 0x52,
	SCAN_KPPERIOD_DEL = 0x53,
};

void handleSDLEvents();
