#pragma once

#include <cstdint>

void restoreErrorInt();
uint32_t curSystemTime();
void restoreVideo();
void hookInts();
void errorQuit(const char* msg, uint16_t error_code);
void hwCheck();
void roundToNextSeg(uint8_t** seg, uint16_t* off);
uint8_t* decompressChunk(uint16_t chunk_id, uint8_t* dst, size_t dst_size);
void allocMemAndLoadData();
void freeMemAndQuit();
void clearSoundBuffers();
void initSound();
void initVideo();
void fadePalStep();
void updateVgaBuffer();
void fadePalKeepFirst();
void zeroInventory();
void initGameState();
void loadLevelHeader(uint16_t level_id);
uint16_t seekLoadList();
uint16_t loadPaletteList(uint16_t di);
uint16_t processLoadList(uint16_t di);
uint16_t loadChunkList(uint16_t di);
uint16_t loadChunkList2(uint16_t di);
void sub_11784();
void sub_11397();
void sub_137F1();
void sub_12FB3();
bool sub_13BBD(uint16_t si, uint16_t di);
void sub_13BA5();
void sub_139EF();
void sub_13A94();
void sub_13A0E();
void sub_115D2();
void calculateRowOffsets(uint16_t level_width);
void calcLevelSize();
void assembleLevelTiles();
void loadImage(uint16_t chunk_id, uint16_t offset);
void loadChunks3();
void loadPal2ToVga();
void fadePalOut();
void fadePalIn();
void drawTile(uint16_t tilegfx_off, uint16_t vram_off);
void drawTilesLine(uint16_t tilemap_off, uint16_t vram_off);
void cloneBackBuffer();
void drawInitialBg();
void updateInitialBg();
void video_clearVRAM();
void drawInventoryItem(uint16_t item_id, uint16_t slot);
void drawInventory();
void drawInventoryReticle(int slot);
void drawInventorySelections();
void drawStatusbar();
void setInitialScreenPos();
bool sub_13D30(uint16_t di);
int findFreeWord29835();
int sub_12F82(uint16_t ax, uint16_t* out_ax);
bool sub_13E52(uint16_t si, uint16_t bx);
bool sub_13809(int16_t ax, uint16_t di, uint16_t si, uint16_t* out_di);
void sub_11446();
void loadNextLevel();
void sub_10138();
void sub_15517();
void sub_14207();
void sub_12CA3();
